// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_lsAVFTWcVe2oX-zSNiivcKxhAd0xPu0',
    appId: '1:579129371110:web:81d63431ae3a1325fd0e27',
    messagingSenderId: '579129371110',
    projectId: 'deenup',
    authDomain: 'deenup.firebaseapp.com',
    storageBucket: 'deenup.firebasestorage.app',
    measurementId: 'G-DEDJLYCC5D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8P-0cS-EUR4l3_5pj6hkDo3WjmNUhkKc',
    appId: '1:579129371110:android:57317a1025828e8ffd0e27',
    messagingSenderId: '579129371110',
    projectId: 'deenup',
    storageBucket: 'deenup.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT4Wi8jgPHimlQRODPiMfuYvK6KPM59Zk',
    appId: '1:579129371110:ios:36fa0d9292ad129afd0e27',
    messagingSenderId: '579129371110',
    projectId: 'deenup',
    storageBucket: 'deenup.firebasestorage.app',
    iosBundleId: 'com.example.deenup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT4Wi8jgPHimlQRODPiMfuYvK6KPM59Zk',
    appId: '1:579129371110:ios:36fa0d9292ad129afd0e27',
    messagingSenderId: '579129371110',
    projectId: 'deenup',
    storageBucket: 'deenup.firebasestorage.app',
    iosBundleId: 'com.example.deenup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_lsAVFTWcVe2oX-zSNiivcKxhAd0xPu0',
    appId: '1:579129371110:web:5592494b108003c5fd0e27',
    messagingSenderId: '579129371110',
    projectId: 'deenup',
    authDomain: 'deenup.firebaseapp.com',
    storageBucket: 'deenup.firebasestorage.app',
    measurementId: 'G-BQBMQR3MX2',
  );
}
